name: Automated Commit

on:
  push:
    branches: [master] # Trigger saat push ke master
  schedule:
    - cron: '0 */8 * * *' # Setiap 8 jam
  workflow_dispatch: # Bisa dijalankan manual

permissions:
  contents: write

jobs:
  update_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Debug Information
        run: echo "::debug::Triggered by ref = ${{ github.ref }}"

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: false # Penting: supaya tidak pakai GITHUB_TOKEN
          fetch-depth: 0

      - name: Update Timestamp File
        run: |
          export TZ="Asia/Jakarta"
          current_time=$(date '+%Y-%m-%d %H:%M:%S')
          echo "Updated on $current_time (WIB)" > TIMESTAMP.txt

      - name: Setup Git Configuration
        run: |
          git config user.email "nadivaaanggraini@gmail.com"
          git config user.name "nadiva-anggraini"

      - name: Prepare Commit
        run: |
          export TZ="Asia/Jakarta"
          current_time=$(date '+%Y-%m-%d %H:%M:%S')
          commit_message="Update at $current_time (WIB)"

          git add TIMESTAMP.txt
          git commit -m "$commit_message" || echo "No changes to commit."

      - name: Push Changes as User
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PRIVATE_SECRET }} # Gunakan PAT kamu
          branch: master
          directory: '.'
